# Generated by Django 4.1.7 on 2023-03-19 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('title', models.CharField(max_length=250, verbose_name='Sarlavhasi')),
                ('slug', models.SlugField(max_length=250, verbose_name='Slugi')),
                ('slider', models.ImageField(upload_to='blog/blog/slider/', verbose_name='Rasm')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
            },
        ),
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('device_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='Qurilma manzili')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.article')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ko`rishlar soni',
                'verbose_name_plural': 'Ko`rishlar soni',
            },
        ),
    ]
