# Generated by Django 4.1.7 on 2023-03-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, verbose_name='Chegirma foizi'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='discout_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Chegirma summasi'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jami summa'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Yetkazib berish narxi'),
        ),
    ]
