# Generated by Django 4.1.7 on 2023-03-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cart_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'verbose_name': 'Savatga tegishli mahsulot', 'verbose_name_plural': 'Savatga tegishli mahsulotlar'},
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jami summa'),
        ),
    ]
