# Generated by Django 4.1.7 on 2023-03-23 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cart', '0005_alter_cartproduct_options_alter_cartitem_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False, verbose_name='Buyurtma qiliganligi'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Mahsulot turi'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='Mahsulot id'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Mahsulotlar soni'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='cart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart', verbose_name='Savat'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cartitem', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart', verbose_name='Savat'),
        ),
    ]
