# Generated by Django 4.1.7 on 2023-03-23 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cart_in_order_alter_cartitem_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='region_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.region', verbose_name='Viloyat'),
            preserve_default=False,
        ),
    ]
