# Generated by Django 4.1.7 on 2023-03-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_district_region_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Yangi'), ('In_progress', 'Jarayoda'), ('Error', 'Xatolik'), ('Completed', 'Bajarildi')], default='In_progress', max_length=20, verbose_name='Buyurtma holati'),
        ),
    ]
