# Generated by Django 4.1.7 on 2023-03-27 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='district',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='district',
            name='title_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='title_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='region',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='region',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='region',
            name='title_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='district_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.district', verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.paymenttype', verbose_name='To`lov turi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='region_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.region', verbose_name='Viloyat'),
        ),
    ]
