# Generated by Django 4.1.7 on 2023-03-19 05:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('phone_number', models.CharField(error_messages={'unique': 'Bu telefon nomer ro`yhatdan o`tgan!'}, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Iltimos telefon nomerni to`g`ri kiriting', regex='^[+][998]{3}?[0-9]{9}$')], verbose_name='Telefon nomer')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Elektron pochta')),
                ('avatar', models.ImageField(default='user/user/avatar/default-user.png', upload_to='user/user/avatar/', verbose_name='Sahifa uchun rasm')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Tug`ilgan sanasi')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Barcha foydalanuvchilar',
            },
        ),
    ]
