# Generated by Django 4.1.7 on 2023-03-23 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveditem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='saveditem',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='Obyekt id'),
        ),
    ]
