# Generated by Django 4.1.7 on 2023-03-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_saveditem_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Ism'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Ism'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Ism'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Familiya'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Familiya'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Familiya'),
        ),
    ]
