# Generated by Django 4.1.7 on 2023-03-27 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_first_name_en_user_first_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name_uz',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name_uz',
        ),
    ]
