# Generated by Django 4.1.7 on 2023-03-19 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('title', models.CharField(max_length=150, verbose_name='Kitob nomi')),
                ('slug', models.SlugField(max_length=150, verbose_name='Slugi')),
                ('total_pages', models.PositiveIntegerField(verbose_name='Sahifalar soni')),
                ('year_of_issue', models.PositiveIntegerField(verbose_name='Ishlab chiqarilgan yili')),
                ('desciption', models.TextField(verbose_name='Kitob haqida ma`lumot')),
                ('slider', models.ImageField(upload_to='education/book/slider/', verbose_name='Rasm')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Narxi')),
                ('is_discount', models.BooleanField(default=False, verbose_name='Chegirma')),
                ('discount_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Chegirmadagi narxi')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.author', verbose_name='Muallif')),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.language', verbose_name='Tili')),
                ('leval_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.leval', verbose_name='Kitob darajasi')),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
            },
        ),
        migrations.CreateModel(
            name='CategoryForCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavhasi')),
                ('slug', models.SlugField(max_length=150, verbose_name='Slugi')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('title', models.CharField(max_length=150, verbose_name='Kurs nomi')),
                ('slug', models.SlugField(max_length=150, verbose_name='Slugi')),
                ('desciption', models.TextField(verbose_name='Kurs haqida ma`lumot')),
                ('slider', models.ImageField(upload_to='education/course/slider/', verbose_name='Rasm')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Narxi')),
                ('is_discount', models.BooleanField(default=False, verbose_name='Chegirma')),
                ('discount_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Chegirmadagi narxi')),
                ('is_free', models.BooleanField(default=False, verbose_name='Bepul')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.author', verbose_name='Muallif')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.categoryforcourse', verbose_name='Kategoriya')),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.language', verbose_name='Tili')),
                ('leval_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.leval', verbose_name='Kurs darajasi')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('title', models.CharField(max_length=150, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=150, verbose_name='Slugi')),
                ('file', models.FileField(upload_to='course/episode/file/', verbose_name='Fayl')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Tartib nomeri')),
                ('length', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
            ],
            options={
                'verbose_name': 'Epizod',
                'verbose_name_plural': 'Epizodlar',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavhasi')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Tartib nomeri')),
                ('section_type', models.CharField(choices=[('Not seen', 'Ko`rilmagan'), ('In progress', 'Jarayonda'), ('Reviewed', 'Ko`rilgan')], default='Not seen', max_length=20, verbose_name='Bo`lim turi')),
                ('is_public', models.BooleanField(default=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.course')),
            ],
            options={
                'verbose_name': 'Bo`lim',
                'verbose_name_plural': 'Bo`limlar',
            },
        ),
        migrations.CreateModel(
            name='PurchasedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.course', verbose_name='Kurs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Sotib olingan kurs',
                'verbose_name_plural': 'Sotib olingan kurslar',
            },
        ),
        migrations.CreateModel(
            name='PurchasedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('qty', models.PositiveIntegerField(verbose_name='Kitoblar soni')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.book', verbose_name='Kurs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Sotib olingan kitob',
                'verbose_name_plural': 'Sotib olingan kitoblar',
            },
        ),
        migrations.CreateModel(
            name='Episode_viewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('episode_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.episode')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video ko`rilganligi',
                'verbose_name_plural': 'Video ko`rilganligi',
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='section_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.section'),
        ),
        migrations.CreateModel(
            name='CompletedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.course', verbose_name='Kurs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Tugatilgan kurs',
                'verbose_name_plural': 'Tugatilgan kurslar',
            },
        ),
    ]
