# Generated by Django 4.1.7 on 2023-03-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_rename_episode_viewed_episodeviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('Not_seen', 'Ko`rilmagan'), ('In_progress', 'Jarayonda'), ('Reviewed', 'Ko`rilgan')], default='Not seen', max_length=20, verbose_name='Bo`lim turi'),
        ),
    ]
