# Generated by Django 4.1.7 on 2023-03-23 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0004_book_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True, verbose_name='Video davomiyligi'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='section_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.section', verbose_name='Bo`lim'),
        ),
        migrations.AlterField(
            model_name='episodeviewed',
            name='episode_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.episode', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='episodeviewed',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='section',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.course', verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='section',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Hamma uchun'),
        ),
    ]
