# Generated by Django 4.1.7 on 2023-03-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desciption_en',
            field=models.TextField(null=True, verbose_name='Kitob haqida ma`lumot'),
        ),
        migrations.AddField(
            model_name='book',
            name='desciption_ru',
            field=models.TextField(null=True, verbose_name='Kitob haqida ma`lumot'),
        ),
        migrations.AddField(
            model_name='book',
            name='desciption_uz',
            field=models.TextField(null=True, verbose_name='Kitob haqida ma`lumot'),
        ),
        migrations.AddField(
            model_name='book',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Kitob nomi'),
        ),
        migrations.AddField(
            model_name='book',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Kitob nomi'),
        ),
        migrations.AddField(
            model_name='book',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Kitob nomi'),
        ),
        migrations.AddField(
            model_name='categoryforcourse',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Sarlavhasi'),
        ),
        migrations.AddField(
            model_name='categoryforcourse',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Sarlavhasi'),
        ),
        migrations.AddField(
            model_name='categoryforcourse',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Sarlavhasi'),
        ),
        migrations.AddField(
            model_name='course',
            name='desciption_en',
            field=models.TextField(null=True, verbose_name='Kurs haqida ma`lumot'),
        ),
        migrations.AddField(
            model_name='course',
            name='desciption_ru',
            field=models.TextField(null=True, verbose_name='Kurs haqida ma`lumot'),
        ),
        migrations.AddField(
            model_name='course',
            name='desciption_uz',
            field=models.TextField(null=True, verbose_name='Kurs haqida ma`lumot'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Kurs nomi'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Kurs nomi'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Kurs nomi'),
        ),
        migrations.AddField(
            model_name='episode',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='episode',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='episode',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='section',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Sarlavhasi'),
        ),
        migrations.AddField(
            model_name='section',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Sarlavhasi'),
        ),
        migrations.AddField(
            model_name='section',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Sarlavhasi'),
        ),
    ]
