# Generated by Django 4.1.7 on 2023-03-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('first_name', models.CharField(max_length=150, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=20, verbose_name='Familiyasi')),
            ],
            options={
                'verbose_name': 'Muallif',
                'verbose_name_plural': 'Mualliflar',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('first_name', models.CharField(max_length=150, verbose_name='Ism')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon nomer')),
                ('message', models.TextField(verbose_name='Xabar')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=20, verbose_name='Slugi')),
            ],
            options={
                'verbose_name': 'Til',
                'verbose_name_plural': 'Tillar',
            },
        ),
        migrations.CreateModel(
            name='Leval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=20, verbose_name='Slugi')),
            ],
            options={
                'verbose_name': 'Daraja',
                'verbose_name_plural': 'Darajalar',
            },
        ),
    ]
