# Generated by Django 4.1.7 on 2023-03-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_reviews_content_type_alter_reviews_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='first_name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Ismi'),
        ),
        migrations.AddField(
            model_name='author',
            name='first_name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Ismi'),
        ),
        migrations.AddField(
            model_name='author',
            name='first_name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Ismi'),
        ),
        migrations.AddField(
            model_name='author',
            name='last_name_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Familiyasi'),
        ),
        migrations.AddField(
            model_name='author',
            name='last_name_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='Familiyasi'),
        ),
        migrations.AddField(
            model_name='author',
            name='last_name_uz',
            field=models.CharField(max_length=20, null=True, verbose_name='Familiyasi'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='leval',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='leval',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='leval',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
    ]
